/**
 * 
 */
package uk.ac.horizon.ug.lobby.model;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

import com.google.appengine.api.datastore.Key;

/**
 * @author cmg
 *
 */
@Entity
public class GameClientTemplate {
	/** key - autogenerated */
    @Id 
    @GeneratedValue(strategy = GenerationType.IDENTITY) 
    private Key key; 
    /** GameTemplate */
    private String gameTemplateId;
    /** client template title */
    private String title;
    /** client type, e.g. "Android" */
    private String clientType;
    /** Android client type */
    public static final String CLIENT_TYPE_ANDROID = "Android";
    /** min major version */
    private int minMajorVersion;
    /** min minor version (or 0) */
    private int minMinorVersion;
    /** min update (or 0) */
    private int minUpdateVersion;
    /** TODO additional requirements? */
    /** required application identifier; on Android this is an intent name to start the app (which 
     * might well include version-specific element(s)).
     */
    private String applicationLaunchId;
    /** on Android this is the packagename of the application, which can (hopefully) be found in
     * the marketplace. See http://developer.android.com/guide/publishing/publishing.html
     */
    private String applicationMarketId;
}
