/**
 * Copyright 2010 The University of Nottingham
 * 
 * This file is part of lobbyservice.
 *
 *  lobbyservice is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  lobbyservice is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with lobbyservice.  If not, see <http://www.gnu.org/licenses/>.
 * 
 */
package uk.ac.horizon.ug.lobby.model;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

import com.google.appengine.api.datastore.Key;

/** A particular client's relationship to a particular GameInstance.
 * 
 * @author cmg
 *
 */
@Entity
public class GameInstanceSlot {
	/** key - autogenerated */
    @Id 
    @GeneratedValue(strategy = GenerationType.IDENTITY) 
    private Key key; 
    /** game instance id */
    private Key gameInstanceId;
    /** game template id (strictly redundant with gameInstance.gameTemplateId) */
    private String gameTemplateId;
    /** client id */
    private Key clientId;
    /** slot status */
    private GameInstanceSlotStatus status;
    /** client shared secret */
    private String clientSharedSecret;
    /** cons */
    public GameInstanceSlot() {    	
    }
	/**
	 * @return the key
	 */
	public Key getKey() {
		return key;
	}
	/**
	 * @param key the key to set
	 */
	public void setKey(Key key) {
		this.key = key;
	}
	/**
	 * @return the gameInstanceId
	 */
	public Key getGameInstanceId() {
		return gameInstanceId;
	}
	/**
	 * @param gameInstanceId the gameInstanceId to set
	 */
	public void setGameInstanceId(Key gameInstanceId) {
		this.gameInstanceId = gameInstanceId;
	}
	/**
	 * @return the gameTemplateId
	 */
	public String getGameTemplateId() {
		return gameTemplateId;
	}
	/**
	 * @param gameTemplateId the gameTemplateId to set
	 */
	public void setGameTemplateId(String gameTemplateId) {
		this.gameTemplateId = gameTemplateId;
	}
	/**
	 * @return the clientId
	 */
	public Key getClientId() {
		return clientId;
	}
	/**
	 * @param clientId the clientId to set
	 */
	public void setClientId(Key clientId) {
		this.clientId = clientId;
	}
	/**
	 * @return the status
	 */
	public GameInstanceSlotStatus getStatus() {
		return status;
	}
	/**
	 * @param status the status to set
	 */
	public void setStatus(GameInstanceSlotStatus status) {
		this.status = status;
	}
	/**
	 * @return the clientSharedSecret
	 */
	public String getClientSharedSecret() {
		return clientSharedSecret;
	}
	/**
	 * @param clientSharedSecret the clientSharedSecret to set
	 */
	public void setClientSharedSecret(String clientSharedSecret) {
		this.clientSharedSecret = clientSharedSecret;
	}
}
